"""Conjunto inicial de alimentos para el catálogo global.

Alimentos españoles comunes con su composición en los 12 nutrientes del seed
(por 100 g) y los tags que les tocan. Sirven para tener datos reales con los que
probar la lectura/escritura y luego el solver.

Los valores son aproximados de BEDCA y USDA, redondeados, por eso source='custom'
(la importación masiva con source_id va aparte). sugar_added_g es 0 en los
alimentos sin procesar porque el azúcar de la fruta no es añadido. Un nutriente
que no aparece en un alimento se trata como "sin dato", no como cero.

Cada alimento lleva además su perfil de ración (Bloque 8e): mínimo y máximo de
gramos por aparición en una comida, y gramos por unidad si se sirve por piezas
(None si va por gramos). Las cantidades se refieren al estado en que el catálogo
describe el alimento (crudo/seco), igual que sus nutrientes. Los roles
(condiment, sweet) y las franjas horarias permitidas (moment_*) van como tags;
un alimento sin tags moment_* puede aparecer en cualquier franja.
"""

from __future__ import annotations

from typing import Optional, TypedDict


class FoodSeed(TypedDict):
    name_es: str
    name_en: str
    typical_serving_g: float
    min_serving_g: int
    max_serving_g: int
    grams_per_unit: Optional[int]
    nutrients: dict[str, float]
    tags: list[str]


# Orden de macros en los dicts: energy, protein, carb, fat, sat_fat, fiber,
# sodium, sugar_added, iron, calcium, vit_d, vit_b12.
FOODS: list[FoodSeed] = [
    {
        "name_es": "Pechuga de pollo, cruda",
        "name_en": "Chicken breast, raw",
        "typical_serving_g": 150,
        "min_serving_g": 100, "max_serving_g": 200, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 110, "protein_g": 23.0, "carb_g": 0.0, "fat_g": 1.9,
                      "sat_fat_g": 0.5, "fiber_g": 0.0, "sodium_mg": 65, "sugar_added_g": 0.0,
                      "iron_mg": 0.7, "calcium_mg": 11, "vit_b12_ug": 0.3},
        "tags": ["halal", "no_pork", "protein_source", "moment_lunch", "moment_dinner"],
    },
    {
        "name_es": "Salmón, crudo",
        "name_en": "Salmon, raw",
        "typical_serving_g": 125,
        "min_serving_g": 100, "max_serving_g": 200, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 208, "protein_g": 20.0, "carb_g": 0.0, "fat_g": 13.0,
                      "sat_fat_g": 3.0, "fiber_g": 0.0, "sodium_mg": 59, "sugar_added_g": 0.0,
                      "iron_mg": 0.8, "calcium_mg": 12, "vit_d_ug": 11.0, "vit_b12_ug": 3.2},
        "tags": ["fish_allergen", "no_pork", "halal", "protein_source", "moment_lunch", "moment_dinner"],
    },
    {
        "name_es": "Huevo de gallina, entero",
        "name_en": "Egg, whole",
        "typical_serving_g": 60,
        "min_serving_g": 60, "max_serving_g": 180, "grams_per_unit": 60,
        "nutrients": {"energy_kcal": 143, "protein_g": 12.6, "carb_g": 0.7, "fat_g": 9.5,
                      "sat_fat_g": 3.1, "fiber_g": 0.0, "sodium_mg": 142, "sugar_added_g": 0.0,
                      "iron_mg": 1.8, "calcium_mg": 56, "vit_d_ug": 2.0, "vit_b12_ug": 1.1},
        "tags": ["eggs_allergen", "vegetarian", "no_pork", "halal", "protein_source"],
    },
    {
        "name_es": "Leche de vaca, semidesnatada",
        "name_en": "Cow's milk, semi-skimmed",
        "typical_serving_g": 200,
        "min_serving_g": 100, "max_serving_g": 300, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 46, "protein_g": 3.3, "carb_g": 4.8, "fat_g": 1.6,
                      "sat_fat_g": 1.0, "fiber_g": 0.0, "sodium_mg": 44, "sugar_added_g": 0.0,
                      "iron_mg": 0.0, "calcium_mg": 120, "vit_d_ug": 0.0, "vit_b12_ug": 0.4},
        "tags": ["milk_allergen", "lactose", "vegetarian", "no_pork", "halal", "dairy"],
    },
    {
        "name_es": "Yogur natural",
        "name_en": "Plain yogurt",
        "typical_serving_g": 125,
        "min_serving_g": 125, "max_serving_g": 250, "grams_per_unit": 125,
        "nutrients": {"energy_kcal": 61, "protein_g": 3.5, "carb_g": 4.7, "fat_g": 3.3,
                      "sat_fat_g": 2.1, "fiber_g": 0.0, "sodium_mg": 46, "sugar_added_g": 0.0,
                      "iron_mg": 0.1, "calcium_mg": 121, "vit_b12_ug": 0.4},
        "tags": ["milk_allergen", "lactose", "vegetarian", "no_pork", "halal", "dairy"],
    },
    {
        "name_es": "Queso curado",
        "name_en": "Cured cheese",
        "typical_serving_g": 40,
        "min_serving_g": 20, "max_serving_g": 60, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 387, "protein_g": 25.0, "carb_g": 1.4, "fat_g": 32.0,
                      "sat_fat_g": 20.0, "fiber_g": 0.0, "sodium_mg": 700, "sugar_added_g": 0.0,
                      "iron_mg": 0.4, "calcium_mg": 850, "vit_d_ug": 0.6, "vit_b12_ug": 1.5},
        "tags": ["milk_allergen", "lactose", "vegetarian", "no_pork", "halal", "high_sodium", "dairy"],
    },
    {
        "name_es": "Arroz blanco, crudo",
        "name_en": "White rice, raw",
        "typical_serving_g": 70,
        "min_serving_g": 50, "max_serving_g": 120, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 354, "protein_g": 7.0, "carb_g": 78.0, "fat_g": 0.6,
                      "sat_fat_g": 0.2, "fiber_g": 1.3, "sodium_mg": 5, "sugar_added_g": 0.0,
                      "iron_mg": 0.8, "calcium_mg": 10},
        "tags": ["vegan", "vegetarian", "no_pork", "halal", "high_gi", "cereal", "moment_lunch", "moment_dinner"],
    },
    {
        "name_es": "Pan blanco de trigo",
        "name_en": "White wheat bread",
        "typical_serving_g": 50,
        "min_serving_g": 30, "max_serving_g": 120, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 265, "protein_g": 9.0, "carb_g": 49.0, "fat_g": 3.2,
                      "sat_fat_g": 0.7, "fiber_g": 2.7, "sodium_mg": 490, "sugar_added_g": 3.0,
                      "iron_mg": 1.5, "calcium_mg": 90},
        "tags": ["gluten", "vegan", "vegetarian", "no_pork", "halal", "high_gi", "high_sodium", "cereal"],
    },
    {
        "name_es": "Copos de avena",
        "name_en": "Oat flakes",
        "typical_serving_g": 40,
        "min_serving_g": 30, "max_serving_g": 80, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 379, "protein_g": 13.0, "carb_g": 58.0, "fat_g": 7.0,
                      "sat_fat_g": 1.2, "fiber_g": 10.0, "sodium_mg": 4, "sugar_added_g": 0.0,
                      "iron_mg": 4.3, "calcium_mg": 52},
        "tags": ["gluten", "vegan", "vegetarian", "no_pork", "halal", "cereal", "moment_breakfast", "moment_mid_morning", "moment_snack"],
    },
    {
        "name_es": "Pasta de trigo, cruda",
        "name_en": "Wheat pasta, raw",
        "typical_serving_g": 75,
        "min_serving_g": 60, "max_serving_g": 125, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 359, "protein_g": 12.5, "carb_g": 71.0, "fat_g": 1.5,
                      "sat_fat_g": 0.3, "fiber_g": 3.0, "sodium_mg": 6, "sugar_added_g": 0.0,
                      "iron_mg": 1.4, "calcium_mg": 22},
        "tags": ["gluten", "vegan", "vegetarian", "no_pork", "halal", "cereal", "moment_lunch", "moment_dinner"],
    },
    {
        "name_es": "Lentejas, secas",
        "name_en": "Lentils, dry",
        "typical_serving_g": 80,
        "min_serving_g": 60, "max_serving_g": 120, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 336, "protein_g": 24.0, "carb_g": 52.0, "fat_g": 1.8,
                      "sat_fat_g": 0.3, "fiber_g": 11.5, "sodium_mg": 24, "sugar_added_g": 0.0,
                      "iron_mg": 7.5, "calcium_mg": 56},
        "tags": ["vegan", "vegetarian", "no_pork", "halal", "fodmap_high", "legume", "moment_lunch", "moment_dinner"],
    },
    {
        "name_es": "Garbanzos, secos",
        "name_en": "Chickpeas, dry",
        "typical_serving_g": 80,
        "min_serving_g": 60, "max_serving_g": 120, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 364, "protein_g": 19.0, "carb_g": 61.0, "fat_g": 6.0,
                      "sat_fat_g": 0.6, "fiber_g": 17.0, "sodium_mg": 24, "sugar_added_g": 0.0,
                      "iron_mg": 6.2, "calcium_mg": 105},
        "tags": ["vegan", "vegetarian", "no_pork", "halal", "fodmap_high", "legume", "moment_lunch", "moment_dinner"],
    },
    {
        "name_es": "Aceite de oliva virgen extra",
        "name_en": "Extra virgin olive oil",
        "typical_serving_g": 10,
        "min_serving_g": 10, "max_serving_g": 20, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 884, "protein_g": 0.0, "carb_g": 0.0, "fat_g": 100.0,
                      "sat_fat_g": 14.0, "fiber_g": 0.0, "sodium_mg": 0, "sugar_added_g": 0.0,
                      "iron_mg": 0.0, "calcium_mg": 1},
        "tags": ["vegan", "vegetarian", "no_pork", "halal", "condiment"],
    },
    {
        "name_es": "Almendras, crudas",
        "name_en": "Almonds, raw",
        "typical_serving_g": 30,
        "min_serving_g": 15, "max_serving_g": 40, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 579, "protein_g": 21.0, "carb_g": 22.0, "fat_g": 50.0,
                      "sat_fat_g": 3.8, "fiber_g": 12.5, "sodium_mg": 1, "sugar_added_g": 0.0,
                      "iron_mg": 3.7, "calcium_mg": 269},
        "tags": ["tree_nuts", "vegan", "vegetarian", "no_pork", "halal"],
    },
    {
        "name_es": "Tomate, crudo",
        "name_en": "Tomato, raw",
        "typical_serving_g": 120,
        "min_serving_g": 50, "max_serving_g": 250, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 18, "protein_g": 0.9, "carb_g": 3.9, "fat_g": 0.2,
                      "sat_fat_g": 0.0, "fiber_g": 1.2, "sodium_mg": 5, "sugar_added_g": 0.0,
                      "iron_mg": 0.3, "calcium_mg": 10},
        "tags": ["vegan", "vegetarian", "no_pork", "halal", "vegetable", "moment_breakfast", "moment_mid_morning", "moment_lunch", "moment_snack", "moment_dinner"],
    },
    {
        "name_es": "Brócoli, crudo",
        "name_en": "Broccoli, raw",
        "typical_serving_g": 150,
        "min_serving_g": 100, "max_serving_g": 250, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 34, "protein_g": 2.8, "carb_g": 7.0, "fat_g": 0.4,
                      "sat_fat_g": 0.1, "fiber_g": 2.6, "sodium_mg": 33, "sugar_added_g": 0.0,
                      "iron_mg": 0.7, "calcium_mg": 47},
        "tags": ["vegan", "vegetarian", "no_pork", "halal", "vegetable", "moment_lunch", "moment_dinner"],
    },
    {
        "name_es": "Espinacas, crudas",
        "name_en": "Spinach, raw",
        "typical_serving_g": 100,
        "min_serving_g": 100, "max_serving_g": 250, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 23, "protein_g": 2.9, "carb_g": 3.6, "fat_g": 0.4,
                      "sat_fat_g": 0.1, "fiber_g": 2.2, "sodium_mg": 79, "sugar_added_g": 0.0,
                      "iron_mg": 2.7, "calcium_mg": 99},
        "tags": ["vegan", "vegetarian", "no_pork", "halal", "high_potassium", "vegetable", "moment_lunch", "moment_dinner"],
    },
    {
        "name_es": "Patata, cruda",
        "name_en": "Potato, raw",
        "typical_serving_g": 180,
        "min_serving_g": 100, "max_serving_g": 300, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 77, "protein_g": 2.0, "carb_g": 17.0, "fat_g": 0.1,
                      "sat_fat_g": 0.0, "fiber_g": 2.2, "sodium_mg": 6, "sugar_added_g": 0.0,
                      "iron_mg": 0.8, "calcium_mg": 12},
        "tags": ["vegan", "vegetarian", "no_pork", "halal", "high_gi", "high_potassium", "cereal", "moment_lunch", "moment_dinner"],
    },
    {
        "name_es": "Manzana, cruda",
        "name_en": "Apple, raw",
        "typical_serving_g": 150,
        "min_serving_g": 75, "max_serving_g": 300, "grams_per_unit": 150,
        "nutrients": {"energy_kcal": 52, "protein_g": 0.3, "carb_g": 14.0, "fat_g": 0.2,
                      "sat_fat_g": 0.0, "fiber_g": 2.4, "sodium_mg": 1, "sugar_added_g": 0.0,
                      "iron_mg": 0.1, "calcium_mg": 6},
        "tags": ["vegan", "vegetarian", "no_pork", "halal", "fruit"],
    },
    {
        "name_es": "Plátano, crudo",
        "name_en": "Banana, raw",
        "typical_serving_g": 120,
        "min_serving_g": 60, "max_serving_g": 240, "grams_per_unit": 120,
        "nutrients": {"energy_kcal": 89, "protein_g": 1.1, "carb_g": 23.0, "fat_g": 0.3,
                      "sat_fat_g": 0.1, "fiber_g": 2.6, "sodium_mg": 1, "sugar_added_g": 0.0,
                      "iron_mg": 0.3, "calcium_mg": 5},
        "tags": ["vegan", "vegetarian", "no_pork", "halal", "high_potassium", "fruit"],
    },
    {
        "name_es": "Atún en conserva al natural",
        "name_en": "Canned tuna in water",
        "typical_serving_g": 80,
        "min_serving_g": 60, "max_serving_g": 120, "grams_per_unit": 60,
        "nutrients": {"energy_kcal": 116, "protein_g": 26.0, "carb_g": 0.0, "fat_g": 1.0,
                      "sat_fat_g": 0.3, "fiber_g": 0.0, "sodium_mg": 320, "sugar_added_g": 0.0,
                      "iron_mg": 1.3, "calcium_mg": 11, "vit_d_ug": 1.7, "vit_b12_ug": 2.2},
        "tags": ["fish_allergen", "no_pork", "halal", "high_sodium", "protein_source", "moment_mid_morning", "moment_lunch", "moment_snack", "moment_dinner"],
    },
    {
        "name_es": "Tofu firme",
        "name_en": "Firm tofu",
        "typical_serving_g": 100,
        "min_serving_g": 80, "max_serving_g": 200, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 144, "protein_g": 15.0, "carb_g": 2.8, "fat_g": 8.7,
                      "sat_fat_g": 1.3, "fiber_g": 2.0, "sodium_mg": 14, "sugar_added_g": 0.0,
                      "iron_mg": 2.7, "calcium_mg": 350},
        "tags": ["soy", "vegan", "vegetarian", "no_pork", "halal", "protein_source", "moment_lunch", "moment_dinner"],
    },
    {
        "name_es": "Ternera magra, cruda",
        "name_en": "Lean beef, raw",
        "typical_serving_g": 150,
        "min_serving_g": 100, "max_serving_g": 200, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 187, "protein_g": 21.0, "carb_g": 0.0, "fat_g": 11.0,
                      "sat_fat_g": 4.5, "fiber_g": 0.0, "sodium_mg": 55, "sugar_added_g": 0.0,
                      "iron_mg": 2.6, "calcium_mg": 12, "vit_b12_ug": 2.5},
        "tags": ["red_meat", "no_pork", "halal", "protein_source", "moment_lunch", "moment_dinner"],
    },
    {
        "name_es": "Pechuga de pavo, cruda",
        "name_en": "Turkey breast, raw",
        "typical_serving_g": 150,
        "min_serving_g": 100, "max_serving_g": 200, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 104, "protein_g": 24.0, "carb_g": 0.0, "fat_g": 1.0,
                      "sat_fat_g": 0.3, "fiber_g": 0.0, "sodium_mg": 63, "sugar_added_g": 0.0,
                      "iron_mg": 1.0, "calcium_mg": 12, "vit_b12_ug": 1.6},
        "tags": ["no_pork", "halal", "protein_source", "moment_lunch", "moment_dinner"],
    },
    {
        "name_es": "Crema de cacahuete",
        "name_en": "Peanut butter",
        "typical_serving_g": 20,
        "min_serving_g": 10, "max_serving_g": 40, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 588, "protein_g": 25.0, "carb_g": 20.0, "fat_g": 50.0,
                      "sat_fat_g": 10.0, "fiber_g": 6.0, "sodium_mg": 17, "sugar_added_g": 5.0,
                      "iron_mg": 1.9, "calcium_mg": 43},
        "tags": ["peanuts", "vegan", "vegetarian", "no_pork", "halal", "condiment"],
    },
    {
        "name_es": "Queso fresco batido desnatado",
        "name_en": "Skim quark",
        "typical_serving_g": 125,
        "min_serving_g": 100, "max_serving_g": 250, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 68, "protein_g": 12.0, "carb_g": 4.0, "fat_g": 0.3,
                      "sat_fat_g": 0.2, "fiber_g": 0.0, "sodium_mg": 40, "sugar_added_g": 0.0,
                      "iron_mg": 0.1, "calcium_mg": 90, "vit_b12_ug": 0.8},
        "tags": ["milk_allergen", "lactose", "vegetarian", "no_pork", "halal", "dairy"],
    },
    {
        "name_es": "Guisantes, crudos",
        "name_en": "Green peas, raw",
        "typical_serving_g": 100,
        "min_serving_g": 100, "max_serving_g": 250, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 81, "protein_g": 5.4, "carb_g": 14.0, "fat_g": 0.4,
                      "sat_fat_g": 0.1, "fiber_g": 5.1, "sodium_mg": 5, "sugar_added_g": 0.0,
                      "iron_mg": 1.5, "calcium_mg": 25},
        "tags": ["vegan", "vegetarian", "no_pork", "halal", "vegetable", "moment_lunch", "moment_dinner"],
    },
    {
        "name_es": "Sardina en conserva",
        "name_en": "Canned sardines",
        "typical_serving_g": 80,
        "min_serving_g": 40, "max_serving_g": 120, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 208, "protein_g": 24.6, "carb_g": 0.0, "fat_g": 11.5,
                      "sat_fat_g": 1.5, "fiber_g": 0.0, "sodium_mg": 307, "sugar_added_g": 0.0,
                      "iron_mg": 2.9, "calcium_mg": 382, "vit_d_ug": 4.8, "vit_b12_ug": 8.9},
        "tags": ["fish_allergen", "no_pork", "halal", "high_sodium", "protein_source", "moment_mid_morning", "moment_lunch", "moment_snack", "moment_dinner"],
    },
    {
        "name_es": "Zanahoria, cruda",
        "name_en": "Carrot, raw",
        "typical_serving_g": 100,
        "min_serving_g": 50, "max_serving_g": 200, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 41, "protein_g": 0.9, "carb_g": 9.6, "fat_g": 0.2,
                      "sat_fat_g": 0.0, "fiber_g": 2.8, "sodium_mg": 69, "sugar_added_g": 0.0,
                      "iron_mg": 0.3, "calcium_mg": 33},
        "tags": ["vegan", "vegetarian", "no_pork", "halal", "vegetable", "moment_mid_morning", "moment_lunch", "moment_snack", "moment_dinner"],
    },
    {
        "name_es": "Calabacín, crudo",
        "name_en": "Zucchini, raw",
        "typical_serving_g": 150,
        "min_serving_g": 100, "max_serving_g": 250, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 17, "protein_g": 1.2, "carb_g": 3.1, "fat_g": 0.3,
                      "sat_fat_g": 0.1, "fiber_g": 1.0, "sodium_mg": 8, "sugar_added_g": 0.0,
                      "iron_mg": 0.4, "calcium_mg": 16},
        "tags": ["vegan", "vegetarian", "no_pork", "halal", "vegetable", "moment_lunch", "moment_dinner"],
    },
    {
        "name_es": "Pimiento rojo, crudo",
        "name_en": "Red bell pepper, raw",
        "typical_serving_g": 120,
        "min_serving_g": 50, "max_serving_g": 200, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 31, "protein_g": 1.0, "carb_g": 6.0, "fat_g": 0.3,
                      "sat_fat_g": 0.1, "fiber_g": 2.1, "sodium_mg": 4, "sugar_added_g": 0.0,
                      "iron_mg": 0.4, "calcium_mg": 7},
        "tags": ["vegan", "vegetarian", "no_pork", "halal", "vegetable", "moment_lunch", "moment_dinner"],
    },
    {
        "name_es": "Cebolla, cruda",
        "name_en": "Onion, raw",
        "typical_serving_g": 100,
        "min_serving_g": 30, "max_serving_g": 100, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 40, "protein_g": 1.1, "carb_g": 9.3, "fat_g": 0.1,
                      "sat_fat_g": 0.0, "fiber_g": 1.7, "sodium_mg": 4, "sugar_added_g": 0.0,
                      "iron_mg": 0.2, "calcium_mg": 23},
        "tags": ["vegan", "vegetarian", "no_pork", "halal", "vegetable", "fodmap_high", "condiment", "moment_lunch", "moment_dinner"],
    },
    {
        "name_es": "Judía verde, cruda",
        "name_en": "Green beans, raw",
        "typical_serving_g": 150,
        "min_serving_g": 100, "max_serving_g": 250, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 31, "protein_g": 1.8, "carb_g": 7.0, "fat_g": 0.2,
                      "sat_fat_g": 0.0, "fiber_g": 3.4, "sodium_mg": 6, "sugar_added_g": 0.0,
                      "iron_mg": 1.0, "calcium_mg": 37},
        "tags": ["vegan", "vegetarian", "no_pork", "halal", "vegetable", "moment_lunch", "moment_dinner"],
    },
    {
        "name_es": "Lechuga, cruda",
        "name_en": "Lettuce, raw",
        "typical_serving_g": 80,
        "min_serving_g": 30, "max_serving_g": 150, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 15, "protein_g": 1.4, "carb_g": 2.9, "fat_g": 0.2,
                      "sat_fat_g": 0.0, "fiber_g": 1.3, "sodium_mg": 28, "sugar_added_g": 0.0,
                      "iron_mg": 0.9, "calcium_mg": 36},
        "tags": ["vegan", "vegetarian", "no_pork", "halal", "vegetable", "moment_lunch", "moment_dinner"],
    },
    {
        "name_es": "Naranja, cruda",
        "name_en": "Orange, raw",
        "typical_serving_g": 150,
        "min_serving_g": 75, "max_serving_g": 300, "grams_per_unit": 150,
        "nutrients": {"energy_kcal": 47, "protein_g": 0.9, "carb_g": 12.0, "fat_g": 0.1,
                      "sat_fat_g": 0.0, "fiber_g": 2.4, "sodium_mg": 0, "sugar_added_g": 0.0,
                      "iron_mg": 0.1, "calcium_mg": 40},
        "tags": ["vegan", "vegetarian", "no_pork", "halal", "fruit"],
    },
    {
        "name_es": "Pera, cruda",
        "name_en": "Pear, raw",
        "typical_serving_g": 160,
        "min_serving_g": 80, "max_serving_g": 320, "grams_per_unit": 160,
        "nutrients": {"energy_kcal": 57, "protein_g": 0.4, "carb_g": 15.0, "fat_g": 0.1,
                      "sat_fat_g": 0.0, "fiber_g": 3.1, "sodium_mg": 1, "sugar_added_g": 0.0,
                      "iron_mg": 0.2, "calcium_mg": 9},
        "tags": ["vegan", "vegetarian", "no_pork", "halal", "fruit"],
    },
    {
        "name_es": "Fresa, cruda",
        "name_en": "Strawberry, raw",
        "typical_serving_g": 120,
        "min_serving_g": 100, "max_serving_g": 250, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 32, "protein_g": 0.7, "carb_g": 7.7, "fat_g": 0.3,
                      "sat_fat_g": 0.0, "fiber_g": 2.0, "sodium_mg": 1, "sugar_added_g": 0.0,
                      "iron_mg": 0.4, "calcium_mg": 16},
        "tags": ["vegan", "vegetarian", "no_pork", "halal", "fruit"],
    },
    {
        "name_es": "Kiwi, crudo",
        "name_en": "Kiwi, raw",
        "typical_serving_g": 100,
        "min_serving_g": 80, "max_serving_g": 160, "grams_per_unit": 80,
        "nutrients": {"energy_kcal": 61, "protein_g": 1.1, "carb_g": 15.0, "fat_g": 0.5,
                      "sat_fat_g": 0.0, "fiber_g": 3.0, "sodium_mg": 3, "sugar_added_g": 0.0,
                      "iron_mg": 0.3, "calcium_mg": 34},
        "tags": ["vegan", "vegetarian", "no_pork", "halal", "fruit"],
    },
    {
        "name_es": "Uva, cruda",
        "name_en": "Grapes, raw",
        "typical_serving_g": 120,
        "min_serving_g": 80, "max_serving_g": 200, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 69, "protein_g": 0.7, "carb_g": 18.0, "fat_g": 0.2,
                      "sat_fat_g": 0.1, "fiber_g": 0.9, "sodium_mg": 2, "sugar_added_g": 0.0,
                      "iron_mg": 0.4, "calcium_mg": 10},
        "tags": ["vegan", "vegetarian", "no_pork", "halal", "fruit", "high_gi"],
    },
    {
        "name_es": "Arroz integral, crudo",
        "name_en": "Brown rice, raw",
        "typical_serving_g": 70,
        "min_serving_g": 50, "max_serving_g": 120, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 362, "protein_g": 7.5, "carb_g": 76.0, "fat_g": 2.7,
                      "sat_fat_g": 0.5, "fiber_g": 3.5, "sodium_mg": 5, "sugar_added_g": 0.0,
                      "iron_mg": 1.5, "calcium_mg": 23},
        "tags": ["vegan", "vegetarian", "no_pork", "halal", "cereal", "moment_lunch", "moment_dinner"],
    },
    {
        "name_es": "Pan integral de trigo",
        "name_en": "Whole wheat bread",
        "typical_serving_g": 50,
        "min_serving_g": 30, "max_serving_g": 120, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 247, "protein_g": 13.0, "carb_g": 41.0, "fat_g": 3.4,
                      "sat_fat_g": 0.7, "fiber_g": 7.0, "sodium_mg": 450, "sugar_added_g": 2.0,
                      "iron_mg": 2.5, "calcium_mg": 107},
        "tags": ["gluten", "vegan", "vegetarian", "no_pork", "halal", "cereal", "high_sodium"],
    },
    {
        "name_es": "Quinoa, cruda",
        "name_en": "Quinoa, raw",
        "typical_serving_g": 70,
        "min_serving_g": 50, "max_serving_g": 100, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 368, "protein_g": 14.0, "carb_g": 64.0, "fat_g": 6.1,
                      "sat_fat_g": 0.7, "fiber_g": 7.0, "sodium_mg": 5, "sugar_added_g": 0.0,
                      "iron_mg": 4.6, "calcium_mg": 47},
        "tags": ["vegan", "vegetarian", "no_pork", "halal", "cereal", "moment_lunch", "moment_dinner"],
    },
    {
        "name_es": "Cuscús, crudo",
        "name_en": "Couscous, raw",
        "typical_serving_g": 70,
        "min_serving_g": 50, "max_serving_g": 100, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 376, "protein_g": 13.0, "carb_g": 77.0, "fat_g": 0.6,
                      "sat_fat_g": 0.1, "fiber_g": 5.0, "sodium_mg": 10, "sugar_added_g": 0.0,
                      "iron_mg": 1.1, "calcium_mg": 24},
        "tags": ["gluten", "vegan", "vegetarian", "no_pork", "halal", "cereal", "moment_lunch", "moment_dinner"],
    },
    {
        "name_es": "Boniato, crudo",
        "name_en": "Sweet potato, raw",
        "typical_serving_g": 180,
        "min_serving_g": 100, "max_serving_g": 300, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 86, "protein_g": 1.6, "carb_g": 20.0, "fat_g": 0.1,
                      "sat_fat_g": 0.0, "fiber_g": 3.0, "sodium_mg": 55, "sugar_added_g": 0.0,
                      "iron_mg": 0.6, "calcium_mg": 30},
        "tags": ["vegan", "vegetarian", "no_pork", "halal", "cereal", "high_potassium", "moment_lunch", "moment_dinner"],
    },
    {
        "name_es": "Maíz dulce, en conserva",
        "name_en": "Sweet corn, canned",
        "typical_serving_g": 80,
        "min_serving_g": 40, "max_serving_g": 140, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 86, "protein_g": 3.2, "carb_g": 19.0, "fat_g": 1.2,
                      "sat_fat_g": 0.2, "fiber_g": 2.7, "sodium_mg": 210, "sugar_added_g": 0.0,
                      "iron_mg": 0.5, "calcium_mg": 2},
        "tags": ["vegan", "vegetarian", "no_pork", "halal", "cereal", "moment_lunch", "moment_dinner"],
    },
    {
        "name_es": "Alubia blanca, seca",
        "name_en": "White beans, dry",
        "typical_serving_g": 80,
        "min_serving_g": 60, "max_serving_g": 120, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 333, "protein_g": 21.0, "carb_g": 60.0, "fat_g": 1.2,
                      "sat_fat_g": 0.3, "fiber_g": 15.0, "sodium_mg": 16, "sugar_added_g": 0.0,
                      "iron_mg": 6.0, "calcium_mg": 143},
        "tags": ["vegan", "vegetarian", "no_pork", "halal", "legume", "fodmap_high", "moment_lunch", "moment_dinner"],
    },
    {
        "name_es": "Guisante seco, partido",
        "name_en": "Split peas, dry",
        "typical_serving_g": 80,
        "min_serving_g": 60, "max_serving_g": 120, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 341, "protein_g": 25.0, "carb_g": 60.0, "fat_g": 1.2,
                      "sat_fat_g": 0.2, "fiber_g": 26.0, "sodium_mg": 15, "sugar_added_g": 0.0,
                      "iron_mg": 4.4, "calcium_mg": 55},
        "tags": ["vegan", "vegetarian", "no_pork", "halal", "legume", "fodmap_high", "moment_lunch", "moment_dinner"],
    },
    {
        "name_es": "Leche de vaca, entera",
        "name_en": "Cow's milk, whole",
        "typical_serving_g": 200,
        "min_serving_g": 100, "max_serving_g": 300, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 63, "protein_g": 3.2, "carb_g": 4.7, "fat_g": 3.6,
                      "sat_fat_g": 2.3, "fiber_g": 0.0, "sodium_mg": 43, "sugar_added_g": 0.0,
                      "iron_mg": 0.0, "calcium_mg": 118, "vit_d_ug": 0.0, "vit_b12_ug": 0.5},
        "tags": ["milk_allergen", "lactose", "vegetarian", "no_pork", "halal", "dairy"],
    },
    {
        "name_es": "Yogur griego",
        "name_en": "Greek yogurt",
        "typical_serving_g": 125,
        "min_serving_g": 125, "max_serving_g": 250, "grams_per_unit": 125,
        "nutrients": {"energy_kcal": 97, "protein_g": 9.0, "carb_g": 3.6, "fat_g": 5.0,
                      "sat_fat_g": 3.3, "fiber_g": 0.0, "sodium_mg": 36, "sugar_added_g": 0.0,
                      "iron_mg": 0.1, "calcium_mg": 100, "vit_b12_ug": 0.5},
        "tags": ["milk_allergen", "lactose", "vegetarian", "no_pork", "halal", "dairy"],
    },
    {
        "name_es": "Requesón",
        "name_en": "Cottage cheese",
        "typical_serving_g": 100,
        "min_serving_g": 50, "max_serving_g": 150, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 98, "protein_g": 11.0, "carb_g": 3.4, "fat_g": 4.3,
                      "sat_fat_g": 1.7, "fiber_g": 0.0, "sodium_mg": 364, "sugar_added_g": 0.0,
                      "iron_mg": 0.1, "calcium_mg": 83, "vit_b12_ug": 0.4},
        "tags": ["milk_allergen", "lactose", "vegetarian", "no_pork", "halal", "dairy", "high_sodium"],
    },
    {
        "name_es": "Merluza, cruda",
        "name_en": "Hake, raw",
        "typical_serving_g": 150,
        "min_serving_g": 100, "max_serving_g": 250, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 72, "protein_g": 17.0, "carb_g": 0.0, "fat_g": 0.8,
                      "sat_fat_g": 0.2, "fiber_g": 0.0, "sodium_mg": 100, "sugar_added_g": 0.0,
                      "iron_mg": 0.4, "calcium_mg": 27, "vit_d_ug": 1.0, "vit_b12_ug": 1.1},
        "tags": ["fish_allergen", "no_pork", "halal", "protein_source", "moment_lunch", "moment_dinner"],
    },
    {
        "name_es": "Gambas, crudas",
        "name_en": "Shrimp, raw",
        "typical_serving_g": 100,
        "min_serving_g": 60, "max_serving_g": 200, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 85, "protein_g": 20.0, "carb_g": 0.2, "fat_g": 0.5,
                      "sat_fat_g": 0.1, "fiber_g": 0.0, "sodium_mg": 224, "sugar_added_g": 0.0,
                      "iron_mg": 0.5, "calcium_mg": 64, "vit_b12_ug": 1.5},
        "tags": ["crustaceans", "no_pork", "halal", "protein_source", "moment_lunch", "moment_dinner"],
    },
    {
        "name_es": "Lomo de cerdo, crudo",
        "name_en": "Pork loin, raw",
        "typical_serving_g": 150,
        "min_serving_g": 100, "max_serving_g": 200, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 143, "protein_g": 21.0, "carb_g": 0.0, "fat_g": 6.0,
                      "sat_fat_g": 2.1, "fiber_g": 0.0, "sodium_mg": 53, "sugar_added_g": 0.0,
                      "iron_mg": 0.9, "calcium_mg": 8, "vit_b12_ug": 0.7},
        "tags": ["protein_source", "moment_lunch", "moment_dinner"],
    },
    {
        "name_es": "Muslo de pollo, crudo",
        "name_en": "Chicken thigh, raw",
        "typical_serving_g": 150,
        "min_serving_g": 100, "max_serving_g": 250, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 121, "protein_g": 20.0, "carb_g": 0.0, "fat_g": 4.3,
                      "sat_fat_g": 1.1, "fiber_g": 0.0, "sodium_mg": 86, "sugar_added_g": 0.0,
                      "iron_mg": 0.9, "calcium_mg": 8, "vit_b12_ug": 0.5},
        "tags": ["no_pork", "halal", "protein_source", "moment_lunch", "moment_dinner"],
    },
    {
        "name_es": "Jamón cocido",
        "name_en": "Cooked ham",
        "typical_serving_g": 50,
        "min_serving_g": 30, "max_serving_g": 120, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 107, "protein_g": 18.0, "carb_g": 1.0, "fat_g": 3.5,
                      "sat_fat_g": 1.2, "fiber_g": 0.0, "sodium_mg": 950, "sugar_added_g": 0.5,
                      "iron_mg": 0.8, "calcium_mg": 8, "vit_b12_ug": 0.6},
        "tags": ["protein_source", "high_sodium", "nova_4"],
    },
    {
        "name_es": "Nueces",
        "name_en": "Walnuts",
        "typical_serving_g": 30,
        "min_serving_g": 15, "max_serving_g": 40, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 654, "protein_g": 15.0, "carb_g": 14.0, "fat_g": 65.0,
                      "sat_fat_g": 6.1, "fiber_g": 6.7, "sodium_mg": 2, "sugar_added_g": 0.0,
                      "iron_mg": 2.9, "calcium_mg": 98},
        "tags": ["tree_nuts", "vegan", "vegetarian", "no_pork", "halal"],
    },
    {
        "name_es": "Aguacate, crudo",
        "name_en": "Avocado, raw",
        "typical_serving_g": 100,
        "min_serving_g": 70, "max_serving_g": 140, "grams_per_unit": 140,
        "nutrients": {"energy_kcal": 160, "protein_g": 2.0, "carb_g": 9.0, "fat_g": 15.0,
                      "sat_fat_g": 2.1, "fiber_g": 6.7, "sodium_mg": 7, "sugar_added_g": 0.0,
                      "iron_mg": 0.6, "calcium_mg": 12},
        "tags": ["vegan", "vegetarian", "no_pork", "halal", "fruit", "high_potassium"],
    },
    {
        "name_es": "Semillas de girasol",
        "name_en": "Sunflower seeds",
        "typical_serving_g": 25,
        "min_serving_g": 10, "max_serving_g": 30, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 584, "protein_g": 21.0, "carb_g": 20.0, "fat_g": 51.0,
                      "sat_fat_g": 4.5, "fiber_g": 8.6, "sodium_mg": 9, "sugar_added_g": 0.0,
                      "iron_mg": 5.2, "calcium_mg": 78},
        "tags": ["vegan", "vegetarian", "no_pork", "halal"],
    },
    {
        "name_es": "Coliflor, cruda",
        "name_en": "Cauliflower, raw",
        "typical_serving_g": 150,
        "min_serving_g": 100, "max_serving_g": 250, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 25, "protein_g": 1.9, "carb_g": 5.0, "fat_g": 0.3,
                      "sat_fat_g": 0.1, "fiber_g": 2.0, "sodium_mg": 30, "sugar_added_g": 0.0,
                      "iron_mg": 0.4, "calcium_mg": 22},
        "tags": ["vegan", "vegetarian", "no_pork", "halal", "vegetable", "moment_lunch", "moment_dinner"],
    },
    {
        "name_es": "Berenjena, cruda",
        "name_en": "Eggplant, raw",
        "typical_serving_g": 150,
        "min_serving_g": 100, "max_serving_g": 250, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 25, "protein_g": 1.0, "carb_g": 6.0, "fat_g": 0.2,
                      "sat_fat_g": 0.0, "fiber_g": 3.0, "sodium_mg": 2, "sugar_added_g": 0.0,
                      "iron_mg": 0.2, "calcium_mg": 9},
        "tags": ["vegan", "vegetarian", "no_pork", "halal", "vegetable", "moment_lunch", "moment_dinner"],
    },
    {
        "name_es": "Pepino, crudo",
        "name_en": "Cucumber, raw",
        "typical_serving_g": 120,
        "min_serving_g": 50, "max_serving_g": 200, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 15, "protein_g": 0.7, "carb_g": 3.6, "fat_g": 0.1,
                      "sat_fat_g": 0.0, "fiber_g": 0.5, "sodium_mg": 2, "sugar_added_g": 0.0,
                      "iron_mg": 0.3, "calcium_mg": 16},
        "tags": ["vegan", "vegetarian", "no_pork", "halal", "vegetable", "moment_mid_morning", "moment_lunch", "moment_snack", "moment_dinner"],
    },
    {
        "name_es": "Champiñón, crudo",
        "name_en": "Button mushroom, raw",
        "typical_serving_g": 100,
        "min_serving_g": 100, "max_serving_g": 250, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 22, "protein_g": 3.1, "carb_g": 3.3, "fat_g": 0.3,
                      "sat_fat_g": 0.1, "fiber_g": 1.0, "sodium_mg": 5, "sugar_added_g": 0.0,
                      "iron_mg": 0.5, "calcium_mg": 3, "vit_d_ug": 0.2},
        "tags": ["vegan", "vegetarian", "no_pork", "halal", "vegetable", "moment_lunch", "moment_dinner"],
    },
    {
        "name_es": "Espárrago verde, crudo",
        "name_en": "Green asparagus, raw",
        "typical_serving_g": 125,
        "min_serving_g": 100, "max_serving_g": 250, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 20, "protein_g": 2.2, "carb_g": 3.9, "fat_g": 0.1,
                      "sat_fat_g": 0.0, "fiber_g": 2.1, "sodium_mg": 2, "sugar_added_g": 0.0,
                      "iron_mg": 2.1, "calcium_mg": 24},
        "tags": ["vegan", "vegetarian", "no_pork", "halal", "vegetable", "moment_lunch", "moment_dinner"],
    },
    {
        "name_es": "Puerro, crudo",
        "name_en": "Leek, raw",
        "typical_serving_g": 120,
        "min_serving_g": 50, "max_serving_g": 200, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 61, "protein_g": 1.5, "carb_g": 14.0, "fat_g": 0.3,
                      "sat_fat_g": 0.0, "fiber_g": 1.8, "sodium_mg": 20, "sugar_added_g": 0.0,
                      "iron_mg": 2.1, "calcium_mg": 59},
        "tags": ["vegan", "vegetarian", "no_pork", "halal", "vegetable", "fodmap_high", "moment_lunch", "moment_dinner"],
    },
    {
        "name_es": "Repollo, crudo",
        "name_en": "White cabbage, raw",
        "typical_serving_g": 150,
        "min_serving_g": 100, "max_serving_g": 250, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 25, "protein_g": 1.3, "carb_g": 5.8, "fat_g": 0.1,
                      "sat_fat_g": 0.0, "fiber_g": 2.5, "sodium_mg": 18, "sugar_added_g": 0.0,
                      "iron_mg": 0.5, "calcium_mg": 40},
        "tags": ["vegan", "vegetarian", "no_pork", "halal", "vegetable", "moment_lunch", "moment_dinner"],
    },
    {
        "name_es": "Acelga, cruda",
        "name_en": "Swiss chard, raw",
        "typical_serving_g": 150,
        "min_serving_g": 100, "max_serving_g": 250, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 19, "protein_g": 1.8, "carb_g": 3.7, "fat_g": 0.2,
                      "sat_fat_g": 0.0, "fiber_g": 1.6, "sodium_mg": 213, "sugar_added_g": 0.0,
                      "iron_mg": 1.8, "calcium_mg": 51},
        "tags": ["vegan", "vegetarian", "no_pork", "halal", "vegetable", "high_potassium", "moment_lunch", "moment_dinner"],
    },
    {
        "name_es": "Remolacha, cruda",
        "name_en": "Beetroot, raw",
        "typical_serving_g": 120,
        "min_serving_g": 50, "max_serving_g": 200, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 43, "protein_g": 1.6, "carb_g": 9.6, "fat_g": 0.2,
                      "sat_fat_g": 0.0, "fiber_g": 2.8, "sodium_mg": 78, "sugar_added_g": 0.0,
                      "iron_mg": 0.8, "calcium_mg": 16},
        "tags": ["vegan", "vegetarian", "no_pork", "halal", "vegetable", "moment_lunch", "moment_dinner"],
    },
    {
        "name_es": "Melón, crudo",
        "name_en": "Melon, raw",
        "typical_serving_g": 200,
        "min_serving_g": 150, "max_serving_g": 300, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 34, "protein_g": 0.8, "carb_g": 8.2, "fat_g": 0.2,
                      "sat_fat_g": 0.0, "fiber_g": 0.9, "sodium_mg": 16, "sugar_added_g": 0.0,
                      "iron_mg": 0.2, "calcium_mg": 9},
        "tags": ["vegan", "vegetarian", "no_pork", "halal", "fruit"],
    },
    {
        "name_es": "Sandía, cruda",
        "name_en": "Watermelon, raw",
        "typical_serving_g": 200,
        "min_serving_g": 150, "max_serving_g": 300, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 30, "protein_g": 0.6, "carb_g": 7.6, "fat_g": 0.2,
                      "sat_fat_g": 0.0, "fiber_g": 0.4, "sodium_mg": 1, "sugar_added_g": 0.0,
                      "iron_mg": 0.2, "calcium_mg": 7},
        "tags": ["vegan", "vegetarian", "no_pork", "halal", "fruit", "high_gi"],
    },
    {
        "name_es": "Piña, cruda",
        "name_en": "Pineapple, raw",
        "typical_serving_g": 150,
        "min_serving_g": 100, "max_serving_g": 250, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 50, "protein_g": 0.5, "carb_g": 13.0, "fat_g": 0.1,
                      "sat_fat_g": 0.0, "fiber_g": 1.4, "sodium_mg": 1, "sugar_added_g": 0.0,
                      "iron_mg": 0.3, "calcium_mg": 13},
        "tags": ["vegan", "vegetarian", "no_pork", "halal", "fruit"],
    },
    {
        "name_es": "Mango, crudo",
        "name_en": "Mango, raw",
        "typical_serving_g": 150,
        "min_serving_g": 100, "max_serving_g": 250, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 60, "protein_g": 0.8, "carb_g": 15.0, "fat_g": 0.4,
                      "sat_fat_g": 0.1, "fiber_g": 1.6, "sodium_mg": 1, "sugar_added_g": 0.0,
                      "iron_mg": 0.2, "calcium_mg": 11},
        "tags": ["vegan", "vegetarian", "no_pork", "halal", "fruit"],
    },
    {
        "name_es": "Melocotón, crudo",
        "name_en": "Peach, raw",
        "typical_serving_g": 150,
        "min_serving_g": 75, "max_serving_g": 300, "grams_per_unit": 150,
        "nutrients": {"energy_kcal": 39, "protein_g": 0.9, "carb_g": 9.5, "fat_g": 0.3,
                      "sat_fat_g": 0.0, "fiber_g": 1.5, "sodium_mg": 0, "sugar_added_g": 0.0,
                      "iron_mg": 0.3, "calcium_mg": 6},
        "tags": ["vegan", "vegetarian", "no_pork", "halal", "fruit"],
    },
    {
        "name_es": "Ciruela, cruda",
        "name_en": "Plum, raw",
        "typical_serving_g": 120,
        "min_serving_g": 60, "max_serving_g": 180, "grams_per_unit": 60,
        "nutrients": {"energy_kcal": 46, "protein_g": 0.7, "carb_g": 11.0, "fat_g": 0.3,
                      "sat_fat_g": 0.0, "fiber_g": 1.4, "sodium_mg": 0, "sugar_added_g": 0.0,
                      "iron_mg": 0.2, "calcium_mg": 6},
        "tags": ["vegan", "vegetarian", "no_pork", "halal", "fruit"],
    },
    {
        "name_es": "Arándano, crudo",
        "name_en": "Blueberry, raw",
        "typical_serving_g": 100,
        "min_serving_g": 50, "max_serving_g": 150, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 57, "protein_g": 0.7, "carb_g": 14.0, "fat_g": 0.3,
                      "sat_fat_g": 0.0, "fiber_g": 2.4, "sodium_mg": 1, "sugar_added_g": 0.0,
                      "iron_mg": 0.3, "calcium_mg": 6},
        "tags": ["vegan", "vegetarian", "no_pork", "halal", "fruit"],
    },
    {
        "name_es": "Bulgur, crudo",
        "name_en": "Bulgur, raw",
        "typical_serving_g": 70,
        "min_serving_g": 50, "max_serving_g": 100, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 342, "protein_g": 12.0, "carb_g": 76.0, "fat_g": 1.3,
                      "sat_fat_g": 0.2, "fiber_g": 18.0, "sodium_mg": 17, "sugar_added_g": 0.0,
                      "iron_mg": 2.5, "calcium_mg": 35},
        "tags": ["gluten", "vegan", "vegetarian", "no_pork", "halal", "cereal", "moment_lunch", "moment_dinner"],
    },
    {
        "name_es": "Pasta integral, cruda",
        "name_en": "Whole wheat pasta, raw",
        "typical_serving_g": 75,
        "min_serving_g": 60, "max_serving_g": 125, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 348, "protein_g": 14.0, "carb_g": 67.0, "fat_g": 2.5,
                      "sat_fat_g": 0.5, "fiber_g": 8.0, "sodium_mg": 8, "sugar_added_g": 0.0,
                      "iron_mg": 3.6, "calcium_mg": 40},
        "tags": ["gluten", "vegan", "vegetarian", "no_pork", "halal", "cereal", "moment_lunch", "moment_dinner"],
    },
    {
        "name_es": "Pan de centeno",
        "name_en": "Rye bread",
        "typical_serving_g": 50,
        "min_serving_g": 30, "max_serving_g": 120, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 259, "protein_g": 8.5, "carb_g": 48.0, "fat_g": 3.3,
                      "sat_fat_g": 0.6, "fiber_g": 5.8, "sodium_mg": 603, "sugar_added_g": 1.0,
                      "iron_mg": 2.8, "calcium_mg": 73},
        "tags": ["gluten", "vegan", "vegetarian", "no_pork", "halal", "cereal", "high_sodium"],
    },
    {
        "name_es": "Tortitas de arroz",
        "name_en": "Rice cakes",
        "typical_serving_g": 20,
        "min_serving_g": 15, "max_serving_g": 45, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 387, "protein_g": 8.2, "carb_g": 82.0, "fat_g": 2.8,
                      "sat_fat_g": 0.6, "fiber_g": 4.2, "sodium_mg": 10, "sugar_added_g": 0.0,
                      "iron_mg": 1.5, "calcium_mg": 11},
        "tags": ["vegan", "vegetarian", "no_pork", "halal", "cereal", "high_gi", "moment_breakfast", "moment_mid_morning", "moment_snack"],
    },
    {
        "name_es": "Cereales de desayuno azucarados",
        "name_en": "Sugary breakfast cereal",
        "typical_serving_g": 40,
        "min_serving_g": 30, "max_serving_g": 60, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 379, "protein_g": 6.0, "carb_g": 84.0, "fat_g": 2.5,
                      "sat_fat_g": 0.7, "fiber_g": 3.0, "sodium_mg": 400, "sugar_added_g": 30.0,
                      "iron_mg": 8.0, "calcium_mg": 20},
        "tags": ["gluten", "vegetarian", "no_pork", "halal", "cereal", "high_gi",
                 "high_sodium", "nova_4", "sweet", "moment_breakfast", "moment_mid_morning", "moment_snack"],
    },
    {
        "name_es": "Mijo, crudo",
        "name_en": "Millet, raw",
        "typical_serving_g": 70,
        "min_serving_g": 40, "max_serving_g": 90, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 378, "protein_g": 11.0, "carb_g": 73.0, "fat_g": 4.2,
                      "sat_fat_g": 0.7, "fiber_g": 8.5, "sodium_mg": 5, "sugar_added_g": 0.0,
                      "iron_mg": 3.0, "calcium_mg": 8},
        "tags": ["vegan", "vegetarian", "no_pork", "halal", "cereal", "moment_breakfast", "moment_lunch", "moment_dinner"],
    },
    {
        "name_es": "Haba seca",
        "name_en": "Dry broad beans",
        "typical_serving_g": 80,
        "min_serving_g": 60, "max_serving_g": 120, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 341, "protein_g": 26.0, "carb_g": 58.0, "fat_g": 1.5,
                      "sat_fat_g": 0.3, "fiber_g": 25.0, "sodium_mg": 13, "sugar_added_g": 0.0,
                      "iron_mg": 6.7, "calcium_mg": 103},
        "tags": ["vegan", "vegetarian", "no_pork", "halal", "legume", "fodmap_high", "moment_lunch", "moment_dinner"],
    },
    {
        "name_es": "Alubia pinta, seca",
        "name_en": "Pinto beans, dry",
        "typical_serving_g": 80,
        "min_serving_g": 60, "max_serving_g": 120, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 347, "protein_g": 21.0, "carb_g": 63.0, "fat_g": 1.2,
                      "sat_fat_g": 0.2, "fiber_g": 15.5, "sodium_mg": 12, "sugar_added_g": 0.0,
                      "iron_mg": 5.1, "calcium_mg": 113},
        "tags": ["vegan", "vegetarian", "no_pork", "halal", "legume", "fodmap_high", "moment_lunch", "moment_dinner"],
    },
    {
        "name_es": "Lenteja roja, seca",
        "name_en": "Red lentils, dry",
        "typical_serving_g": 80,
        "min_serving_g": 60, "max_serving_g": 120, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 358, "protein_g": 24.0, "carb_g": 63.0, "fat_g": 1.1,
                      "sat_fat_g": 0.2, "fiber_g": 11.0, "sodium_mg": 7, "sugar_added_g": 0.0,
                      "iron_mg": 7.4, "calcium_mg": 51},
        "tags": ["vegan", "vegetarian", "no_pork", "halal", "legume", "fodmap_high", "moment_lunch", "moment_dinner"],
    },
    {
        "name_es": "Edamame",
        "name_en": "Edamame",
        "typical_serving_g": 100,
        "min_serving_g": 50, "max_serving_g": 150, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 121, "protein_g": 12.0, "carb_g": 8.9, "fat_g": 5.2,
                      "sat_fat_g": 0.6, "fiber_g": 5.2, "sodium_mg": 6, "sugar_added_g": 0.0,
                      "iron_mg": 2.3, "calcium_mg": 63},
        "tags": ["soy", "vegan", "vegetarian", "no_pork", "halal", "legume", "moment_lunch", "moment_snack", "moment_dinner"],
    },
    {
        "name_es": "Leche de vaca, desnatada",
        "name_en": "Cow's milk, skimmed",
        "typical_serving_g": 200,
        "min_serving_g": 100, "max_serving_g": 300, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 34, "protein_g": 3.4, "carb_g": 5.0, "fat_g": 0.2,
                      "sat_fat_g": 0.1, "fiber_g": 0.0, "sodium_mg": 42, "sugar_added_g": 0.0,
                      "iron_mg": 0.0, "calcium_mg": 122, "vit_b12_ug": 0.4},
        "tags": ["milk_allergen", "lactose", "vegetarian", "no_pork", "halal", "dairy"],
    },
    {
        "name_es": "Kéfir",
        "name_en": "Kefir",
        "typical_serving_g": 200,
        "min_serving_g": 100, "max_serving_g": 250, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 60, "protein_g": 3.4, "carb_g": 4.4, "fat_g": 3.0,
                      "sat_fat_g": 2.0, "fiber_g": 0.0, "sodium_mg": 40, "sugar_added_g": 0.0,
                      "iron_mg": 0.1, "calcium_mg": 120, "vit_b12_ug": 0.3},
        "tags": ["milk_allergen", "lactose", "vegetarian", "no_pork", "halal", "dairy"],
    },
    {
        "name_es": "Mozzarella",
        "name_en": "Mozzarella",
        "typical_serving_g": 60,
        "min_serving_g": 30, "max_serving_g": 125, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 254, "protein_g": 18.0, "carb_g": 2.2, "fat_g": 19.0,
                      "sat_fat_g": 12.0, "fiber_g": 0.0, "sodium_mg": 486, "sugar_added_g": 0.0,
                      "iron_mg": 0.4, "calcium_mg": 505, "vit_d_ug": 0.4, "vit_b12_ug": 1.0},
        "tags": ["milk_allergen", "lactose", "vegetarian", "no_pork", "halal", "dairy",
                 "high_sodium"],
    },
    {
        "name_es": "Queso de cabra",
        "name_en": "Goat cheese",
        "typical_serving_g": 40,
        "min_serving_g": 20, "max_serving_g": 60, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 364, "protein_g": 22.0, "carb_g": 2.5, "fat_g": 30.0,
                      "sat_fat_g": 21.0, "fiber_g": 0.0, "sodium_mg": 515, "sugar_added_g": 0.0,
                      "iron_mg": 1.6, "calcium_mg": 298, "vit_b12_ug": 0.2},
        "tags": ["milk_allergen", "lactose", "vegetarian", "no_pork", "halal", "dairy",
                 "high_sodium"],
    },
    {
        "name_es": "Queso azul",
        "name_en": "Blue cheese",
        "typical_serving_g": 30,
        "min_serving_g": 15, "max_serving_g": 40, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 353, "protein_g": 21.0, "carb_g": 2.3, "fat_g": 29.0,
                      "sat_fat_g": 19.0, "fiber_g": 0.0, "sodium_mg": 1395, "sugar_added_g": 0.0,
                      "iron_mg": 0.3, "calcium_mg": 528, "vit_b12_ug": 1.2},
        "tags": ["milk_allergen", "lactose", "vegetarian", "no_pork", "halal", "dairy",
                 "high_sodium", "high_phosphorus", "condiment"],
    },
    {
        "name_es": "Bacalao, crudo",
        "name_en": "Cod, raw",
        "typical_serving_g": 150,
        "min_serving_g": 100, "max_serving_g": 250, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 82, "protein_g": 18.0, "carb_g": 0.0, "fat_g": 0.7,
                      "sat_fat_g": 0.1, "fiber_g": 0.0, "sodium_mg": 54, "sugar_added_g": 0.0,
                      "iron_mg": 0.4, "calcium_mg": 16, "vit_d_ug": 0.9, "vit_b12_ug": 0.9},
        "tags": ["fish_allergen", "no_pork", "halal", "protein_source", "moment_lunch", "moment_dinner"],
    },
    {
        "name_es": "Caballa, cruda",
        "name_en": "Mackerel, raw",
        "typical_serving_g": 125,
        "min_serving_g": 100, "max_serving_g": 200, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 205, "protein_g": 19.0, "carb_g": 0.0, "fat_g": 14.0,
                      "sat_fat_g": 3.3, "fiber_g": 0.0, "sodium_mg": 90, "sugar_added_g": 0.0,
                      "iron_mg": 1.6, "calcium_mg": 12, "vit_d_ug": 8.2, "vit_b12_ug": 8.7},
        "tags": ["fish_allergen", "no_pork", "halal", "protein_source", "moment_lunch", "moment_dinner"],
    },
    {
        "name_es": "Mejillón, crudo",
        "name_en": "Mussels, raw",
        "typical_serving_g": 100,
        "min_serving_g": 60, "max_serving_g": 200, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 86, "protein_g": 12.0, "carb_g": 3.7, "fat_g": 2.2,
                      "sat_fat_g": 0.4, "fiber_g": 0.0, "sodium_mg": 286, "sugar_added_g": 0.0,
                      "iron_mg": 4.0, "calcium_mg": 26, "vit_d_ug": 0.2, "vit_b12_ug": 12.0},
        "tags": ["mollusks_allergen", "no_pork", "halal", "protein_source", "moment_lunch", "moment_dinner"],
    },
    {
        "name_es": "Calamar, crudo",
        "name_en": "Squid, raw",
        "typical_serving_g": 120,
        "min_serving_g": 100, "max_serving_g": 250, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 92, "protein_g": 16.0, "carb_g": 3.1, "fat_g": 1.4,
                      "sat_fat_g": 0.4, "fiber_g": 0.0, "sodium_mg": 44, "sugar_added_g": 0.0,
                      "iron_mg": 0.7, "calcium_mg": 32, "vit_b12_ug": 1.3},
        "tags": ["mollusks_allergen", "no_pork", "halal", "protein_source", "moment_lunch", "moment_dinner"],
    },
    {
        "name_es": "Pierna de cordero, cruda",
        "name_en": "Lamb leg, raw",
        "typical_serving_g": 150,
        "min_serving_g": 100, "max_serving_g": 250, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 201, "protein_g": 18.0, "carb_g": 0.0, "fat_g": 14.0,
                      "sat_fat_g": 6.2, "fiber_g": 0.0, "sodium_mg": 65, "sugar_added_g": 0.0,
                      "iron_mg": 1.6, "calcium_mg": 9, "vit_b12_ug": 2.6},
        "tags": ["red_meat", "no_pork", "halal", "protein_source", "moment_lunch", "moment_dinner"],
    },
    {
        "name_es": "Tempeh",
        "name_en": "Tempeh",
        "typical_serving_g": 100,
        "min_serving_g": 80, "max_serving_g": 200, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 193, "protein_g": 19.0, "carb_g": 9.4, "fat_g": 11.0,
                      "sat_fat_g": 2.2, "fiber_g": 1.4, "sodium_mg": 9, "sugar_added_g": 0.0,
                      "iron_mg": 2.7, "calcium_mg": 111, "vit_b12_ug": 0.1},
        "tags": ["soy", "vegan", "vegetarian", "no_pork", "halal", "protein_source", "moment_lunch", "moment_dinner"],
    },
    {
        "name_es": "Clara de huevo",
        "name_en": "Egg white",
        "typical_serving_g": 100,
        "min_serving_g": 30, "max_serving_g": 200, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 52, "protein_g": 11.0, "carb_g": 0.7, "fat_g": 0.2,
                      "sat_fat_g": 0.0, "fiber_g": 0.0, "sodium_mg": 166, "sugar_added_g": 0.0,
                      "iron_mg": 0.1, "calcium_mg": 7, "vit_b12_ug": 0.1},
        "tags": ["eggs_allergen", "vegetarian", "no_pork", "halal", "protein_source", "moment_breakfast", "moment_lunch", "moment_dinner"],
    },
    {
        "name_es": "Pistachos",
        "name_en": "Pistachios",
        "typical_serving_g": 30,
        "min_serving_g": 15, "max_serving_g": 40, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 562, "protein_g": 20.0, "carb_g": 28.0, "fat_g": 45.0,
                      "sat_fat_g": 5.5, "fiber_g": 10.3, "sodium_mg": 1, "sugar_added_g": 0.0,
                      "iron_mg": 3.9, "calcium_mg": 105},
        "tags": ["tree_nuts", "vegan", "vegetarian", "no_pork", "halal"],
    },
    {
        "name_es": "Avellanas",
        "name_en": "Hazelnuts",
        "typical_serving_g": 30,
        "min_serving_g": 15, "max_serving_g": 40, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 628, "protein_g": 15.0, "carb_g": 17.0, "fat_g": 61.0,
                      "sat_fat_g": 4.5, "fiber_g": 9.7, "sodium_mg": 0, "sugar_added_g": 0.0,
                      "iron_mg": 4.7, "calcium_mg": 114},
        "tags": ["tree_nuts", "vegan", "vegetarian", "no_pork", "halal"],
    },
    {
        "name_es": "Aceituna verde",
        "name_en": "Green olives",
        "typical_serving_g": 30,
        "min_serving_g": 20, "max_serving_g": 60, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 145, "protein_g": 1.0, "carb_g": 3.8, "fat_g": 15.0,
                      "sat_fat_g": 2.0, "fiber_g": 3.3, "sodium_mg": 1556, "sugar_added_g": 0.0,
                      "iron_mg": 0.5, "calcium_mg": 52},
        "tags": ["vegan", "vegetarian", "no_pork", "halal", "high_sodium", "condiment"],
    },
    {
        "name_es": "Aceite de girasol",
        "name_en": "Sunflower oil",
        "typical_serving_g": 10,
        "min_serving_g": 10, "max_serving_g": 20, "grams_per_unit": None,
        "nutrients": {"energy_kcal": 884, "protein_g": 0.0, "carb_g": 0.0, "fat_g": 100.0,
                      "sat_fat_g": 10.3, "fiber_g": 0.0, "sodium_mg": 0, "sugar_added_g": 0.0},
        "tags": ["vegan", "vegetarian", "no_pork", "halal", "condiment"],
    },
]
